# Generated by Django 4.1.4 on 2022-12-21 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='empmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmpName', models.CharField(max_length=75)),
                ('EmpId', models.IntegerField()),
                ('Designation', models.CharField(max_length=50)),
                ('Dateofjoin', models.DateTimeField()),
                ('Department', models.CharField(max_length=75)),
                ('Salary', models.IntegerField()),
                ('Experience', models.CharField(max_length=50)),
            ],
        ),
    ]
