# Generated by Django 4.1.4 on 2022-12-21 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a2zapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empmodel',
            name='Dateofjoin',
            field=models.CharField(max_length=15),
        ),
    ]
