# Generated by Django 4.1.4 on 2022-12-22 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a2zapp', '0003_calender_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='occation',
            field=models.TextField(),
        ),
    ]
