# Generated by Django 4.1.4 on 2022-12-22 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a2zapp', '0004_alter_news_occation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calender',
            name='Occation',
            field=models.TextField(),
        ),
    ]
